name: Build Windows Executable with DirectX SDK

env:
  DXSDK_DIR: C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1

    - name: Cache DirectX SDK
      id: DXSDK_Jun10
      uses: actions/cache@v4
      with:
        path: ${{env.DXSDK_DIR}}
        key: DXSDK_Jun10
    - name: Install DirectX SDK
      if: steps.DXSDK_Jun10.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        Invoke-WebRequest -Method Get -Uri https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -OutFile DXSDK_Jun10.exe -UseBasicParsing
        Start-Process -Wait ./DXSDK_Jun10.exe -ArgumentList "/U"
    - name: Set DXSDK_DIR
      run: echo "DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\" >> $env:GITHUB_ENV

    - name: Compile C++ code
      run: |
        cl /EHsc main.cpp /link /LIBPATH:"C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\Lib\x86" dinput8.lib dxguid.lib /out:force_feedback.exe

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: force_feedback
        path: force_feedback.exe
